# moonraker.conf — minimal first-boot config for Moonraker

[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /tmp/klippy_uds

[file_manager]
config_path: /etc/klipper
log_path: /var/log/klipper
enable_object_processing: True

[authorization]
force_logins: False
cors_domains:
    *://*.local
    *://app.fluidd.xyz
    *://my.mainsail.xyz
    http://*
trusted_clients:
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128

[octoprint_compat]

[history]

[update_manager]
channel: dev
refresh_interval: 168

[update_manager fluidd]
type: web
channel: stable
repo: fluidd-core/fluidd
path: /var/www/fluidd
